name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and Cypress run
      # https://github.com/cypress-io/github-action
      - name: npx cypress run --browser chrome
        uses: cypress-io/github-action@v5
        with: 
          browser: chrome
