name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and Cypress run
      # https://github.com/cypress-io/github-action
      - name: Write the cypress.env.json file 📝
        run: |
          echo '${{ secrets.TEST_URL }}'
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with: 
          browser: chrome
          
      - name: Upload Cypress test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
         name: cypress-videos
         path: cypress/videos
